[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["nyanko teacher"]
packages = [
    { include = "python_algorithm", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
